# Generated by Django 3.1.7 on 2021-11-03 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha en la que fue creado el registro.', verbose_name='creado en')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha en la que fue modificado el registro.', verbose_name='mmodificado en')),
                ('name', models.CharField(help_text='Nombre del producto', max_length=100, verbose_name='Nombre')),
                ('price', models.IntegerField(help_text='Precio del producto', verbose_name='Precio')),
                ('amount', models.IntegerField(help_text='Cantidad de productos', verbose_name='Cantidad')),
                ('code', models.CharField(max_length=11, verbose_name='Codigo')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripcion del producto')),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
