# Generated by Django 3.1.7 on 2021-11-03 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(max_length=11, unique=True, verbose_name='Codigo'),
        ),
    ]
