# Generated by Django 3.1.7 on 2021-11-04 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20211103_0315'),
        ('invoice', '0002_invoices'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoicesDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha en la que fue creado el registro.', verbose_name='creado en')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha en la que fue modificado el registro.', verbose_name='mmodificado en')),
                ('total_line', models.BigIntegerField(verbose_name='Total factura: ')),
                ('amount', models.IntegerField(verbose_name='cantidad')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='invoice.invoices')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.product')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
