# Generated by Django 3.1.7 on 2021-11-02 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha en la que fue creado el registro.', verbose_name='creado en')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha en la que fue modificado el registro.', verbose_name='mmodificado en')),
                ('name', models.CharField(help_text='Nmbre del cliente o empresa', max_length=50, verbose_name='Nombre')),
                ('rtn', models.CharField(help_text='RTN de la empresa', max_length=16, verbose_name='RTN')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha en la que fue creado el registro.', verbose_name='creado en')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha en la que fue modificado el registro.', verbose_name='mmodificado en')),
                ('first_name', models.CharField(help_text='Primer nombre del vendedor', max_length=20, verbose_name='Nombre')),
                ('last_name', models.CharField(help_text='Apellido del vendedor', max_length=20, verbose_name='Apellido')),
                ('code', models.CharField(error_messages={'unique': 'El codigo debe ser unico'}, max_length=8, unique=True, verbose_name='Codigo de acceso')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
